/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AkatsukiHotel;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivan Adcan
 */
public class SignUp extends javax.swing.JFrame {
    
    /**
     * Creates new form Login
     */
    public SignUp() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        panelWrapper = new javax.swing.JPanel();
        panelLeft = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        panelRight = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        text4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        text5 = new javax.swing.JLabel();
        text7 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        others = new javax.swing.JRadioButton();
        lname = new javax.swing.JTextField();
        text8 = new javax.swing.JLabel();
        dd1 = new javax.swing.JLabel();
        dd6 = new javax.swing.JLabel();
        dd4 = new javax.swing.JLabel();
        dd2 = new javax.swing.JLabel();
        dd3 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        text9 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        dd7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        text6 = new javax.swing.JLabel();
        dd5 = new javax.swing.JLabel();
        text10 = new javax.swing.JLabel();
        dd8 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        text11 = new javax.swing.JLabel();
        dd9 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        birthday = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(839, 530));
        setResizable(false);

        panelWrapper.setBackground(new java.awt.Color(230, 192, 104));
        panelWrapper.setMinimumSize(new java.awt.Dimension(800, 500));
        panelWrapper.setPreferredSize(new java.awt.Dimension(800, 500));
        panelWrapper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLeft.setBackground(new java.awt.Color(28, 42, 57));
        panelLeft.setMinimumSize(new java.awt.Dimension(400, 500));
        panelLeft.setPreferredSize(new java.awt.Dimension(400, 500));
        panelLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        panelLeft.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 113, 240, 235));

        panelWrapper.add(panelLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 387, 474));
        panelLeft.getAccessibleContext().setAccessibleName("panelRight");

        panelRight.setBackground(new java.awt.Color(255, 255, 255));
        panelRight.setMinimumSize(new java.awt.Dimension(400, 500));
        panelRight.setPreferredSize(new java.awt.Dimension(400, 500));

        text1.setBackground(new java.awt.Color(0, 0, 0));
        text1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        text1.setForeground(new java.awt.Color(28, 42, 57));
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setText("Sign Up");

        text2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        text2.setText("First Name");

        text3.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        text3.setText("Last Name");

        fname.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        text4.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        text4.setText("Username");

        username.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        text5.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        text5.setText("Email");

        text7.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        text7.setText("Gender");

        male.setBackground(new java.awt.Color(255, 255, 255));
        gender.add(male);
        male.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        male.setText("Male");
        male.setFocusable(false);
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        female.setBackground(new java.awt.Color(255, 255, 255));
        gender.add(female);
        female.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        female.setText("Female");
        female.setFocusable(false);

        others.setBackground(new java.awt.Color(255, 255, 255));
        gender.add(others);
        others.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        others.setText("Others");
        others.setFocusable(false);

        lname.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        text8.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        text8.setText("Birthday");

        dd1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        dd1.setText(":");

        dd6.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        dd6.setText(":");

        dd4.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        dd4.setText(":");

        dd2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        dd2.setText(":");

        dd3.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        dd3.setText(":");

        signup.setBackground(new java.awt.Color(28, 42, 57));
        signup.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("Sign Up");
        signup.setBorder(null);
        signup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signup.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        signup.setFocusPainted(false);
        signup.setFocusable(false);
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        text9.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        text9.setText("Already have an account?");

        login.setBackground(new java.awt.Color(0, 0, 0));
        login.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        login.setForeground(new java.awt.Color(0, 104, 104));
        login.setText("Login");
        login.setContentAreaFilled(false);
        login.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        login.setFocusable(false);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        dd7.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        dd7.setText(":");

        email.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        text6.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        text6.setText("Password");

        dd5.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        dd5.setText(":");

        text10.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        text10.setText("Phone No.");

        dd8.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        dd8.setText(":");

        phone.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneKeyTyped(evt);
            }
        });

        text11.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        text11.setText("Address");

        dd9.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        dd9.setText(":");

        address.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        birthday.setDate(new java.util.Date(946656000000L));
        birthday.setDateFormatString("dd-MM-yyyy");
        birthday.setFocusCycleRoot(true);

        javax.swing.GroupLayout panelRightLayout = new javax.swing.GroupLayout(panelRight);
        panelRight.setLayout(panelRightLayout);
        panelRightLayout.setHorizontalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelRightLayout.createSequentialGroup()
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRightLayout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(dd1)
                            .addGap(5, 5, 5)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(dd2)
                            .addGap(5, 5, 5)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelRightLayout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(dd3)
                            .addGap(5, 5, 5)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelRightLayout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(text5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(dd4)
                            .addGap(5, 5, 5)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelRightLayout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(text6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(dd5)
                            .addGap(5, 5, 5)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelRightLayout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(text7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(dd6)
                            .addGap(1, 1, 1)
                            .addComponent(male)
                            .addGap(4, 4, 4)
                            .addComponent(female)
                            .addGap(4, 4, 4)
                            .addComponent(others))
                        .addGroup(panelRightLayout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(text9))
                        .addGroup(panelRightLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(text10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(dd8)
                            .addGap(5, 5, 5)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelRightLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(text11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(dd9)
                            .addGap(5, 5, 5)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelRightLayout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panelRightLayout.createSequentialGroup()
                                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelRightLayout.createSequentialGroup()
                                    .addComponent(text8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(7, 7, 7)
                                    .addComponent(dd7)
                                    .addGap(280, 280, 280))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRightLayout.setVerticalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRightLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(text1)
                .addGap(18, 18, 18)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text2)
                            .addComponent(dd1)
                            .addComponent(text3)
                            .addComponent(dd2))))
                .addGap(7, 7, 7)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text4)
                            .addComponent(dd3))))
                .addGap(7, 7, 7)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text5)
                            .addComponent(dd4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text10)
                            .addComponent(dd8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text11)
                            .addComponent(dd9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text6)
                            .addComponent(dd5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(male)
                    .addComponent(female)
                    .addComponent(others)
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text7)
                            .addComponent(dd6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text8)
                    .addComponent(dd7)
                    .addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(text9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        panelWrapper.add(panelRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 13, 422, 474));
        panelRight.getAccessibleContext().setAccessibleName("panelRight");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        
        String g;
 
        if (male.isSelected()) {
            g = "Male";
        } else if (female.isSelected()) {
            g = "Female";
        } else if (others.isSelected()) {
            g = "Others";
        } else {
            g = "";
        }
        
        String bd;
        bd = sdf.format(birthday.getDate());
        
        String firstname, lastname, usern, em, mobile, addres, pw, gend, birthd;
            firstname = this.fname.getText();
            lastname = this.lname.getText();
            usern = this.username.getText();
            em = this.email.getText();
            mobile = this.phone.getText();
            addres = this.address.getText();
            pw = this.password.getText();
            gend = g;
            birthd = bd;
        String SUrl, SUser, SPass, query, queryt;
            SUrl = "jdbc:MySQL://localhost:3306/akatsukihotel_user_database";
            SUser = "root";
            SPass = "";
        
        System.out.println("Sign up button clicked!");
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement stAddUser, stCreateUserTable, stCheckUser, stFindNewUser;
                stAddUser = con.createStatement();
                stCreateUserTable = con.createStatement();
                stCheckUser = con.createStatement();
                stFindNewUser = con.createStatement();
            
            String queryS = "SELECT * FROM user WHERE username = '" + usern + "' OR email = '" + em + "' OR phone = '" + mobile + "'";
            ResultSet rsCheckUser = stCheckUser.executeQuery(queryS);
            
            if ("".equals(firstname)) {
                JOptionPane.showMessageDialog(new JFrame(), "First Name is required!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(lastname)) {
                JOptionPane.showMessageDialog(new JFrame(), "Last Name is required!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(usern)) {
                JOptionPane.showMessageDialog(new JFrame(), "Username is required!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(em)) {
                JOptionPane.showMessageDialog(new JFrame(), "Email is required!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(mobile)) {
                JOptionPane.showMessageDialog(new JFrame(), "Phone is required!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(addres)) {
                JOptionPane.showMessageDialog(new JFrame(), "Address is required!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(pw)) {
                JOptionPane.showMessageDialog(new JFrame(), "Password is required!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(gend)) {
                JOptionPane.showMessageDialog(new JFrame(), "Gender is required!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(birthd)) {
                JOptionPane.showMessageDialog(new JFrame(), "Birthday is required!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (rsCheckUser.next()) {
                    JOptionPane.showMessageDialog(new JFrame(), "Username, email, or phone no. already existed!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    query = "INSERT INTO user(first_name, last_name, username, email, phone, address, password, gender, birthday, old) " +
                            "VALUES('" + firstname + "', '" + lastname + "', '" + usern + "', '" + em + "', '" + mobile + "', '" + addres + "', '" + pw + "', '" + gend + "', '" + birthd + "', 0)";
                    stAddUser.execute(query);
                    
                    ResultSet rsFindNewUser = stFindNewUser.executeQuery(queryS);
                    
                    if (rsFindNewUser.next()) {
                        String getNewUserID = rsFindNewUser.getString("id");
                        
                        queryt = "CREATE TABLE u" + getNewUserID + " ("
                                + "id INT(11) NOT NULL AUTO_INCREMENT,"
                                + "DateBooked varchar(127) NOT NULL,"
                                + "RoomType varchar(127) NOT NULL,"
                                + "Price varchar(127) NOT NULL,"
                                + "RoomSchedule varchar(127) NOT NULL,"
                                + "PRIMARY KEY (id)"
                                + ");";

                        stCreateUserTable.execute(queryt);

                        SignedUp signedup = new SignedUp();
                        signedup.setVisible(true);
                        signedup.pack();
                        signedup.setLocationRelativeTo(null);
                        this.dispose(); 
                    } else {
                        JOptionPane.showMessageDialog(new JFrame(), "Failed to create new user's database.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } 
        }catch (ClassNotFoundException | SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(new JFrame(), "Something wrong with the code of the program.", "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_signupActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_loginActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_phoneKeyTyped

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private com.toedter.calendar.JDateChooser birthday;
    private javax.swing.JLabel dd1;
    private javax.swing.JLabel dd2;
    private javax.swing.JLabel dd3;
    private javax.swing.JLabel dd4;
    private javax.swing.JLabel dd5;
    private javax.swing.JLabel dd6;
    private javax.swing.JLabel dd7;
    private javax.swing.JLabel dd8;
    private javax.swing.JLabel dd9;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JTextField lname;
    public javax.swing.JButton login;
    private javax.swing.JLabel logo;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton others;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel panelWrapper;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JButton signup;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text10;
    private javax.swing.JLabel text11;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text6;
    private javax.swing.JLabel text7;
    private javax.swing.JLabel text8;
    private javax.swing.JLabel text9;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
