/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import java.awt.Color;

/**
 *
 * @author Ivan Adcan
 */
public class reserve extends javax.swing.JPanel {

    /**
     * Creates new form home
     */
    public reserve() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        book1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        book2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        book3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        book = new javax.swing.JButton();
        textWelcom1 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1022, 1314));
        setPreferredSize(new java.awt.Dimension(1022, 1314));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VIP Room");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 405, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reservevippic1.jpg"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        book1.setBackground(new java.awt.Color(255, 255, 255));
        book1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        book1.setForeground(new java.awt.Color(230, 192, 104));
        book1.setText("Book");
        book1.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book1MouseExited(evt);
            }
        });
        book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book1ActionPerformed(evt);
            }
        });
        jPanel2.add(book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 223, 52));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Small Room");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 406, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reservesmallpic1.jpg"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 49, -1, -1));

        book2.setBackground(new java.awt.Color(255, 255, 255));
        book2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        book2.setForeground(new java.awt.Color(230, 192, 104));
        book2.setText("Book");
        book2.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book2MouseExited(evt);
            }
        });
        book2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book2ActionPerformed(evt);
            }
        });
        jPanel3.add(book2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 223, 52));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Medium Room");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 406, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 178, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reservemediumpic1.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        book3.setBackground(new java.awt.Color(255, 255, 255));
        book3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        book3.setForeground(new java.awt.Color(230, 192, 104));
        book3.setText("Book");
        book3.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book3MouseExited(evt);
            }
        });
        book3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book3ActionPerformed(evt);
            }
        });
        jPanel5.add(book3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 223, 52));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Large Room");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 405, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reservelargepic1.jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        book.setBackground(new java.awt.Color(255, 255, 255));
        book.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        book.setForeground(new java.awt.Color(230, 192, 104));
        book.setText("Book");
        book.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookMouseExited(evt);
            }
        });
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        jPanel6.add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 223, 52));

        textWelcom1.setFont(new java.awt.Font("Baskerville Old Face", 1, 48)); // NOI18N
        textWelcom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textWelcom1.setText("Book a Hotel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(textWelcom1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(textWelcom1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseEntered
        Color gold;
        gold = new Color(230,192,104);
        book.setBackground(gold);
        book.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_bookMouseEntered

    private void bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseExited
        Color gold;
        gold = new Color(230,192,104);
        book.setBackground(new Color(255,255,255));
        book.setForeground(gold);
    }//GEN-LAST:event_bookMouseExited

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed

    }//GEN-LAST:event_bookActionPerformed

    private void book1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book1MouseEntered
        Color gold;
        gold = new Color(230,192,104);
        book1.setBackground(gold);
        book1.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_book1MouseEntered

    private void book1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book1MouseExited
        Color gold;
        gold = new Color(230,192,104);
        book1.setBackground(new Color(255,255,255));
        book1.setForeground(gold);
    }//GEN-LAST:event_book1MouseExited

    private void book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book1ActionPerformed

    }//GEN-LAST:event_book1ActionPerformed

    private void book2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book2MouseEntered
        Color gold;
        gold = new Color(230,192,104);
        book2.setBackground(gold);
        book2.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_book2MouseEntered

    private void book2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book2MouseExited
        Color gold;
        gold = new Color(230,192,104);
        book2.setBackground(new Color(255,255,255));
        book2.setForeground(gold);
    }//GEN-LAST:event_book2MouseExited

    private void book2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book2ActionPerformed

    private void book3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book3MouseEntered
        Color gold;
        gold = new Color(230,192,104);
        book3.setBackground(gold);
        book3.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_book3MouseEntered

    private void book3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book3MouseExited
        Color gold;
        gold = new Color(230,192,104);
        book3.setBackground(new Color(255,255,255));
        book3.setForeground(gold);
    }//GEN-LAST:event_book3MouseExited

    private void book3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton book;
    public javax.swing.JButton book1;
    public javax.swing.JButton book2;
    public javax.swing.JButton book3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel textWelcom1;
    // End of variables declaration//GEN-END:variables
}
