/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loggedin;

import AkatsukiHotel.*;

/**
 *
 * @author Ivan Adcan
 */
public class PWForgot extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public PWForgot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWrapper = new javax.swing.JPanel();
        panelLeft = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        panelRight = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        sendcode = new javax.swing.JButton();
        changepw = new javax.swing.JButton();
        code = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forgot Password");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelWrapper.setBackground(new java.awt.Color(230, 192, 104));
        panelWrapper.setMinimumSize(new java.awt.Dimension(800, 500));
        panelWrapper.setPreferredSize(new java.awt.Dimension(800, 500));
        panelWrapper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLeft.setBackground(new java.awt.Color(28, 42, 57));
        panelLeft.setMinimumSize(new java.awt.Dimension(400, 500));
        panelLeft.setPreferredSize(new java.awt.Dimension(400, 500));
        panelLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        panelLeft.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 113, 240, 235));

        panelWrapper.add(panelLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 387, 474));
        panelLeft.getAccessibleContext().setAccessibleName("panelRight");

        panelRight.setBackground(new java.awt.Color(255, 255, 255));
        panelRight.setMinimumSize(new java.awt.Dimension(400, 500));
        panelRight.setPreferredSize(new java.awt.Dimension(400, 500));
        panelRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text1.setBackground(new java.awt.Color(0, 0, 0));
        text1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        text1.setForeground(new java.awt.Color(28, 42, 57));
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setText("Forgot Password");
        panelRight.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 31, 310, -1));

        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Enter Email, Username or Phone Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 13))); // NOI18N
        panelRight.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 288, 50));

        sendcode.setBackground(new java.awt.Color(28, 42, 57));
        sendcode.setForeground(new java.awt.Color(255, 255, 255));
        sendcode.setText("Send Code");
        sendcode.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        sendcode.setFocusable(false);
        sendcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendcodeActionPerformed(evt);
            }
        });
        panelRight.add(sendcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 117, -1, 40));

        changepw.setBackground(new java.awt.Color(0, 104, 104));
        changepw.setForeground(new java.awt.Color(255, 255, 255));
        changepw.setText("Change Password");
        changepw.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        changepw.setFocusable(false);
        changepw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepwActionPerformed(evt);
            }
        });
        panelRight.add(changepw, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 230, 140, 37));

        code.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        code.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 13))); // NOI18N
        panelRight.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 100, 50));

        jPasswordField1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jPasswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Enter New Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 13))); // NOI18N
        panelRight.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 288, 50));

        panelWrapper.add(panelRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 13, 422, 474));
        panelRight.getAccessibleContext().setAccessibleName("panelRight");

        getContentPane().add(panelWrapper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 833, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendcodeActionPerformed

    }//GEN-LAST:event_sendcodeActionPerformed

    private void changepwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepwActionPerformed
        ChangedPW changepw = new ChangedPW();
        changepw.setVisible(true);
        changepw.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_changepwActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton changepw;
    private javax.swing.JTextField code;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel panelWrapper;
    public javax.swing.JButton sendcode;
    private javax.swing.JLabel text1;
    // End of variables declaration//GEN-END:variables
}
