/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loggedin;

import AkatsukiHotel.Login;
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author Ivan Adcan
 */
public class Reserve extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Reserve() {
        initComponents();
    }
    
    public void bgGoldfgWhite() {
        Color gold;
        gold = new Color(230,192,104);
        setBackground(gold);
        setForeground(new Color(255,255,255));
    }
    public void bgWhitefgGold() {
        Color gold;
        gold = new Color(230,192,104);
        setBackground(new Color(255,255,255));
        setForeground(gold);
    }
    
    public void sidepanelChoice(int choice) {
        Home home = new Home();
        Reserve reserve = new Reserve();
        Gallery gallery = new Gallery();
        Contact contact = new Contact();
        About about = new About();
        Profile profile = new Profile();
        
        int c = choice;
        if (c == 0) {
            home.setVisible(true);
            home.setLocationRelativeTo(null);
        }
        if (c == 1) {
            reserve.setVisible(true);
            reserve.setLocationRelativeTo(null);
        }
        if (c == 2) {
            gallery.setVisible(true);
            gallery.setLocationRelativeTo(null);
        }
        if (c == 3) {
            contact.setVisible(true);
            contact.setLocationRelativeTo(null);
        }
        if (c == 4) {
            about.setVisible(true);
            about.setLocationRelativeTo(null);
        }
        if (c == 5) {
            profile.setVisible(true);
            profile.setLocationRelativeTo(null);
        }
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWrapper = new javax.swing.JPanel();
        toppanel = new javax.swing.JPanel();
        textQuote = new javax.swing.JLabel();
        textWelcom = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        gallery1 = new javax.swing.JButton();
        sidepanel = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        reserve = new javax.swing.JButton();
        gallery = new javax.swing.JButton();
        contact = new javax.swing.JButton();
        about = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        insidepanel = new javax.swing.JPanel();
        panelReserve = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        textWelcom4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        book = new javax.swing.JButton();
        book1 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        book2 = new javax.swing.JButton();
        book3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        book4 = new javax.swing.JButton();
        book5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        book6 = new javax.swing.JButton();
        book7 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        book10 = new javax.swing.JButton();
        book11 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        book12 = new javax.swing.JButton();
        book13 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        book14 = new javax.swing.JButton();
        book15 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        book8 = new javax.swing.JButton();
        book9 = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        book20 = new javax.swing.JButton();
        book21 = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        book18 = new javax.swing.JButton();
        book19 = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        book16 = new javax.swing.JButton();
        book17 = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        book22 = new javax.swing.JButton();
        book23 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Akatsuki Hotel Inc.");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        panelWrapper.setBackground(new java.awt.Color(255, 255, 255));
        panelWrapper.setMinimumSize(new java.awt.Dimension(1300, 870));
        panelWrapper.setPreferredSize(new java.awt.Dimension(1900, 980));

        toppanel.setBackground(new java.awt.Color(28, 42, 57));

        textQuote.setFont(new java.awt.Font("Freestyle Script", 0, 30)); // NOI18N
        textQuote.setForeground(new java.awt.Color(255, 255, 255));
        textQuote.setText("Your home away from home");

        textWelcom.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        textWelcom.setForeground(new java.awt.Color(255, 255, 255));
        textWelcom.setText("Akatsuki Hotel Inc.");

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoMini.png"))); // NOI18N

        gallery1.setBackground(new java.awt.Color(255, 255, 255));
        gallery1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        gallery1.setForeground(new java.awt.Color(255, 255, 255));
        gallery1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profile.png"))); // NOI18N
        gallery1.setBorderPainted(false);
        gallery1.setContentAreaFilled(false);
        gallery1.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        gallery1.setFocusable(false);
        gallery1.setPreferredSize(new java.awt.Dimension(80, 80));
        gallery1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gallery1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gallery1FocusLost(evt);
            }
        });
        gallery1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gallery1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gallery1MouseExited(evt);
            }
        });
        gallery1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gallery1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toppanelLayout = new javax.swing.GroupLayout(toppanel);
        toppanel.setLayout(toppanelLayout);
        toppanelLayout.setHorizontalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textWelcom)
                    .addGroup(toppanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(textQuote)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gallery1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        toppanelLayout.setVerticalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(textWelcom)
                .addGap(4, 4, 4)
                .addComponent(textQuote))
            .addGroup(toppanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(toppanelLayout.createSequentialGroup()
                        .addComponent(gallery1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        sidepanel.setBackground(new java.awt.Color(28, 42, 57));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        home.setText("Home");
        home.setBorderPainted(false);
        home.setContentAreaFilled(false);
        home.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        home.setFocusable(false);
        home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        home.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                homeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                homeFocusLost(evt);
            }
        });
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        sidepanel.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 35, 171, -1));

        reserve.setBackground(new java.awt.Color(255, 255, 255));
        reserve.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        reserve.setForeground(new java.awt.Color(255, 255, 255));
        reserve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reserve.png"))); // NOI18N
        reserve.setText("Reserve");
        reserve.setBorderPainted(false);
        reserve.setContentAreaFilled(false);
        reserve.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        reserve.setFocusable(false);
        reserve.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reserve.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reserveFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                reserveFocusLost(evt);
            }
        });
        reserve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reserveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reserveMouseExited(evt);
            }
        });
        reserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveActionPerformed(evt);
            }
        });
        sidepanel.add(reserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 111, 171, -1));

        gallery.setBackground(new java.awt.Color(255, 255, 255));
        gallery.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        gallery.setForeground(new java.awt.Color(255, 255, 255));
        gallery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/gallery.png"))); // NOI18N
        gallery.setText("Gallery");
        gallery.setBorderPainted(false);
        gallery.setContentAreaFilled(false);
        gallery.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        gallery.setFocusable(false);
        gallery.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gallery.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                galleryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                galleryFocusLost(evt);
            }
        });
        gallery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                galleryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                galleryMouseExited(evt);
            }
        });
        gallery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galleryActionPerformed(evt);
            }
        });
        sidepanel.add(gallery, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 187, 171, -1));

        contact.setBackground(new java.awt.Color(255, 255, 255));
        contact.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 255, 255));
        contact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/contact.png"))); // NOI18N
        contact.setText("Contact");
        contact.setBorderPainted(false);
        contact.setContentAreaFilled(false);
        contact.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        contact.setFocusable(false);
        contact.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactMouseExited(evt);
            }
        });
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        sidepanel.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 641, 171, -1));

        about.setBackground(new java.awt.Color(255, 255, 255));
        about.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        about.setForeground(new java.awt.Color(255, 255, 255));
        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/about.png"))); // NOI18N
        about.setText("About");
        about.setBorderPainted(false);
        about.setContentAreaFilled(false);
        about.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        about.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        about.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aboutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                aboutFocusLost(evt);
            }
        });
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutMouseExited(evt);
            }
        });
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        sidepanel.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 722, -1, -1));

        logout.setBackground(new java.awt.Color(255, 0, 0));
        logout.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        logout.setText("Log Out");
        logout.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        sidepanel.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 803, 171, -1));

        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sidepanel-bg-gold.png"))); // NOI18N
        sidepanel.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 96, 260, 70));

        insidepanel.setBackground(new java.awt.Color(255, 255, 255));
        insidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelReserve.setBackground(new java.awt.Color(255, 255, 255));
        panelReserve.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1700, 2009));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textWelcom4.setFont(new java.awt.Font("Baskerville Old Face", 1, 100)); // NOI18N
        textWelcom4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textWelcom4.setText("Reserve a Hotel");
        jPanel3.add(textWelcom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1700, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VIP Room");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel1.setText("P 12,999.99 per night");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, 20));

        book.setBackground(new java.awt.Color(255, 255, 255));
        book.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book.setForeground(new java.awt.Color(230, 192, 104));
        book.setText("Details");
        book.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book.setFocusable(false);
        book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookMouseExited(evt);
            }
        });
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        jPanel4.add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 100, 40));

        book1.setBackground(new java.awt.Color(255, 255, 255));
        book1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book1.setForeground(new java.awt.Color(230, 192, 104));
        book1.setText("Book");
        book1.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book1.setFocusable(false);
        book1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book1MouseExited(evt);
            }
        });
        book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book1ActionPerformed(evt);
            }
        });
        jPanel4.add(book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 90, 40));

        jPanel17.setMaximumSize(new java.awt.Dimension(380, 380));
        jPanel17.setMinimumSize(new java.awt.Dimension(380, 380));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 380));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 170, 400, 570));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Small Room");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel2.setText("P 2,499.99 per night");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, 20));

        book2.setBackground(new java.awt.Color(255, 255, 255));
        book2.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book2.setForeground(new java.awt.Color(230, 192, 104));
        book2.setText("Details");
        book2.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book2.setFocusable(false);
        book2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book2MouseExited(evt);
            }
        });
        book2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book2ActionPerformed(evt);
            }
        });
        jPanel5.add(book2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 100, 40));

        book3.setBackground(new java.awt.Color(255, 255, 255));
        book3.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book3.setForeground(new java.awt.Color(230, 192, 104));
        book3.setText("Book");
        book3.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book3.setFocusable(false);
        book3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book3MouseExited(evt);
            }
        });
        book3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book3ActionPerformed(evt);
            }
        });
        jPanel5.add(book3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 90, 40));

        jPanel1.setMaximumSize(new java.awt.Dimension(380, 380));
        jPanel1.setMinimumSize(new java.awt.Dimension(380, 380));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 380));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 400, 570));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Medium Room");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel6.setText("P 4,999.99 per night");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 180, 20));

        book4.setBackground(new java.awt.Color(255, 255, 255));
        book4.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book4.setForeground(new java.awt.Color(230, 192, 104));
        book4.setText("Details");
        book4.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book4.setFocusable(false);
        book4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book4MouseExited(evt);
            }
        });
        book4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book4ActionPerformed(evt);
            }
        });
        jPanel6.add(book4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 100, 40));

        book5.setBackground(new java.awt.Color(255, 255, 255));
        book5.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book5.setForeground(new java.awt.Color(230, 192, 104));
        book5.setText("Book");
        book5.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book5.setFocusable(false);
        book5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book5MouseExited(evt);
            }
        });
        book5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book5ActionPerformed(evt);
            }
        });
        jPanel6.add(book5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 90, 40));

        jPanel2.setMaximumSize(new java.awt.Dimension(380, 380));
        jPanel2.setMinimumSize(new java.awt.Dimension(380, 380));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 380));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 400, 570));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Large Room");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel8.setText("P 7,499.99 per night");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, 20));

        book6.setBackground(new java.awt.Color(255, 255, 255));
        book6.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book6.setForeground(new java.awt.Color(230, 192, 104));
        book6.setText("Details");
        book6.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book6.setFocusable(false);
        book6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book6MouseExited(evt);
            }
        });
        book6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book6ActionPerformed(evt);
            }
        });
        jPanel7.add(book6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 100, 40));

        book7.setBackground(new java.awt.Color(255, 255, 255));
        book7.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book7.setForeground(new java.awt.Color(230, 192, 104));
        book7.setText("Book");
        book7.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book7.setFocusable(false);
        book7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book7MouseExited(evt);
            }
        });
        book7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book7ActionPerformed(evt);
            }
        });
        jPanel7.add(book7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 90, 40));

        jPanel16.setMaximumSize(new java.awt.Dimension(380, 380));
        jPanel16.setMinimumSize(new java.awt.Dimension(380, 380));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 380));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 400, 570));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("null");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel12.setText("null");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, 20));

        book10.setBackground(new java.awt.Color(255, 255, 255));
        book10.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book10.setForeground(new java.awt.Color(230, 192, 104));
        book10.setText("Details");
        book10.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book10.setFocusable(false);
        book10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book10MouseExited(evt);
            }
        });
        book10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book10ActionPerformed(evt);
            }
        });
        jPanel9.add(book10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 100, 40));

        book11.setBackground(new java.awt.Color(255, 255, 255));
        book11.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book11.setForeground(new java.awt.Color(230, 192, 104));
        book11.setText("Book");
        book11.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book11.setFocusable(false);
        book11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book11MouseExited(evt);
            }
        });
        book11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book11ActionPerformed(evt);
            }
        });
        jPanel9.add(book11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 90, 40));

        jPanel20.setMaximumSize(new java.awt.Dimension(380, 380));
        jPanel20.setMinimumSize(new java.awt.Dimension(380, 380));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 380));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 770, -1, 570));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("null");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel14.setText("null");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, 20));

        book12.setBackground(new java.awt.Color(255, 255, 255));
        book12.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book12.setForeground(new java.awt.Color(230, 192, 104));
        book12.setText("Details");
        book12.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book12.setFocusable(false);
        book12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book12MouseExited(evt);
            }
        });
        book12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book12ActionPerformed(evt);
            }
        });
        jPanel10.add(book12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 100, 40));

        book13.setBackground(new java.awt.Color(255, 255, 255));
        book13.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book13.setForeground(new java.awt.Color(230, 192, 104));
        book13.setText("Book");
        book13.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book13.setFocusable(false);
        book13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book13MouseExited(evt);
            }
        });
        book13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book13ActionPerformed(evt);
            }
        });
        jPanel10.add(book13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 90, 40));

        jPanel19.setMaximumSize(new java.awt.Dimension(380, 380));
        jPanel19.setMinimumSize(new java.awt.Dimension(380, 380));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 380));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 770, -1, 570));

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("null");
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel16.setText("null");
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, 20));

        book14.setBackground(new java.awt.Color(255, 255, 255));
        book14.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book14.setForeground(new java.awt.Color(230, 192, 104));
        book14.setText("Details");
        book14.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book14.setFocusable(false);
        book14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book14MouseExited(evt);
            }
        });
        book14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book14ActionPerformed(evt);
            }
        });
        jPanel11.add(book14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 100, 40));

        book15.setBackground(new java.awt.Color(255, 255, 255));
        book15.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book15.setForeground(new java.awt.Color(230, 192, 104));
        book15.setText("Book");
        book15.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book15.setFocusable(false);
        book15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book15MouseExited(evt);
            }
        });
        book15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book15ActionPerformed(evt);
            }
        });
        jPanel11.add(book15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 90, 40));

        jPanel18.setMaximumSize(new java.awt.Dimension(380, 380));
        jPanel18.setMinimumSize(new java.awt.Dimension(380, 380));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 380));

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 770, -1, 570));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("null");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel10.setText("null");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, 20));

        book8.setBackground(new java.awt.Color(255, 255, 255));
        book8.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book8.setForeground(new java.awt.Color(230, 192, 104));
        book8.setText("Details");
        book8.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book8.setFocusable(false);
        book8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book8MouseExited(evt);
            }
        });
        book8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book8ActionPerformed(evt);
            }
        });
        jPanel8.add(book8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 100, 40));

        book9.setBackground(new java.awt.Color(255, 255, 255));
        book9.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book9.setForeground(new java.awt.Color(230, 192, 104));
        book9.setText("Book");
        book9.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book9.setFocusable(false);
        book9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book9MouseExited(evt);
            }
        });
        book9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book9ActionPerformed(evt);
            }
        });
        jPanel8.add(book9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 90, 40));

        jPanel21.setMaximumSize(new java.awt.Dimension(380, 380));
        jPanel21.setMinimumSize(new java.awt.Dimension(380, 380));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 380));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 770, 400, 570));

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("null");
        jPanel14.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel22.setText("null");
        jPanel14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, 20));

        book20.setBackground(new java.awt.Color(255, 255, 255));
        book20.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book20.setForeground(new java.awt.Color(230, 192, 104));
        book20.setText("Details");
        book20.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book20.setFocusable(false);
        book20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book20MouseExited(evt);
            }
        });
        book20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book20ActionPerformed(evt);
            }
        });
        jPanel14.add(book20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 100, 40));

        book21.setBackground(new java.awt.Color(255, 255, 255));
        book21.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book21.setForeground(new java.awt.Color(230, 192, 104));
        book21.setText("Book");
        book21.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book21.setFocusable(false);
        book21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book21MouseExited(evt);
            }
        });
        book21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book21ActionPerformed(evt);
            }
        });
        jPanel14.add(book21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 90, 40));

        jPanel23.setMaximumSize(new java.awt.Dimension(380, 380));
        jPanel23.setMinimumSize(new java.awt.Dimension(380, 380));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 380));

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 1370, -1, 570));

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("null");
        jPanel13.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel20.setText("null");
        jPanel13.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, 20));

        book18.setBackground(new java.awt.Color(255, 255, 255));
        book18.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book18.setForeground(new java.awt.Color(230, 192, 104));
        book18.setText("Details");
        book18.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book18.setFocusable(false);
        book18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book18MouseExited(evt);
            }
        });
        book18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book18ActionPerformed(evt);
            }
        });
        jPanel13.add(book18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 100, 40));

        book19.setBackground(new java.awt.Color(255, 255, 255));
        book19.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book19.setForeground(new java.awt.Color(230, 192, 104));
        book19.setText("Book");
        book19.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book19.setFocusable(false);
        book19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book19MouseExited(evt);
            }
        });
        book19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book19ActionPerformed(evt);
            }
        });
        jPanel13.add(book19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 90, 40));

        jPanel24.setMaximumSize(new java.awt.Dimension(380, 380));
        jPanel24.setMinimumSize(new java.awt.Dimension(380, 380));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 380));

        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 1370, -1, 570));

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("null");
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel18.setText("null");
        jPanel12.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, 20));

        book16.setBackground(new java.awt.Color(255, 255, 255));
        book16.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book16.setForeground(new java.awt.Color(230, 192, 104));
        book16.setText("Details");
        book16.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book16.setFocusable(false);
        book16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book16MouseExited(evt);
            }
        });
        book16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book16ActionPerformed(evt);
            }
        });
        jPanel12.add(book16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 100, 40));

        book17.setBackground(new java.awt.Color(255, 255, 255));
        book17.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book17.setForeground(new java.awt.Color(230, 192, 104));
        book17.setText("Book");
        book17.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book17.setFocusable(false);
        book17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book17MouseExited(evt);
            }
        });
        book17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book17ActionPerformed(evt);
            }
        });
        jPanel12.add(book17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 90, 40));

        jPanel25.setMaximumSize(new java.awt.Dimension(380, 380));
        jPanel25.setMinimumSize(new java.awt.Dimension(380, 380));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 380));

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 1370, 400, 570));

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("null");
        jPanel15.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel24.setText("null");
        jPanel15.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, 20));

        book22.setBackground(new java.awt.Color(255, 255, 255));
        book22.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book22.setForeground(new java.awt.Color(230, 192, 104));
        book22.setText("Details");
        book22.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book22.setFocusable(false);
        book22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book22MouseExited(evt);
            }
        });
        book22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book22ActionPerformed(evt);
            }
        });
        jPanel15.add(book22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 100, 40));

        book23.setBackground(new java.awt.Color(255, 255, 255));
        book23.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        book23.setForeground(new java.awt.Color(230, 192, 104));
        book23.setText("Book");
        book23.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        book23.setFocusable(false);
        book23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                book23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                book23MouseExited(evt);
            }
        });
        book23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book23ActionPerformed(evt);
            }
        });
        jPanel15.add(book23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 90, 40));

        jPanel22.setMaximumSize(new java.awt.Dimension(380, 380));
        jPanel22.setMinimumSize(new java.awt.Dimension(380, 380));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 380));

        jPanel3.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1370, -1, 570));

        jScrollPane1.setViewportView(jPanel3);

        panelReserve.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 880));

        insidepanel.add(panelReserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 880));

        javax.swing.GroupLayout panelWrapperLayout = new javax.swing.GroupLayout(panelWrapper);
        panelWrapper.setLayout(panelWrapperLayout);
        panelWrapperLayout.setHorizontalGroup(
            panelWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelWrapperLayout.createSequentialGroup()
                .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(insidepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelWrapperLayout.setVerticalGroup(
            panelWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWrapperLayout.createSequentialGroup()
                .addComponent(toppanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 874, Short.MAX_VALUE)
                    .addComponent(sidepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int out = JOptionPane.showConfirmDialog(null, "Do you really want to logout?", "Select", JOptionPane.YES_NO_OPTION);
        if (out == 0) {
            Login login = new Login();
            this.setVisible(false);
            login.setVisible(true);
            login.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        this.sidepanelChoice(4);
    }//GEN-LAST:event_aboutActionPerformed

    private void aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseExited
        Color white;
        white = new Color(255,255,255);
        about.setForeground(white);
    }//GEN-LAST:event_aboutMouseExited

    private void aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseEntered
        Color gold;
        gold = new Color(230,192,104);
        about.setForeground(gold);
    }//GEN-LAST:event_aboutMouseEntered

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
       this.sidepanelChoice(3);
    }//GEN-LAST:event_contactActionPerformed

    private void contactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseExited
        Color white;
        white = new Color(255,255,255);
        contact.setForeground(white);
    }//GEN-LAST:event_contactMouseExited

    private void contactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseEntered
        Color gold;
        gold = new Color(230,192,104);
        contact.setForeground(gold);
    }//GEN-LAST:event_contactMouseEntered

    private void galleryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galleryActionPerformed
       this.sidepanelChoice(2);
    }//GEN-LAST:event_galleryActionPerformed

    private void galleryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_galleryMouseExited
        Color white;
        white = new Color(255,255,255);
        gallery.setForeground(white);
    }//GEN-LAST:event_galleryMouseExited

    private void galleryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_galleryMouseEntered
        Color gold;
        gold = new Color(230,192,104);
        gallery.setForeground(gold);
    }//GEN-LAST:event_galleryMouseEntered

    private void reserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveActionPerformed
       
    }//GEN-LAST:event_reserveActionPerformed

    private void reserveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserveMouseExited
        
    }//GEN-LAST:event_reserveMouseExited

    private void reserveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserveMouseEntered

    }//GEN-LAST:event_reserveMouseEntered

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        Color gold;
        gold = new Color(230,192,104);
        home.setForeground(gold);
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        Color white = new Color(255,255,255);
        home.setForeground(white);
    }//GEN-LAST:event_homeMouseExited

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        this.sidepanelChoice(0);
    }//GEN-LAST:event_homeActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked

    }//GEN-LAST:event_homeMouseClicked

    private void homeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeFocusGained
       
    }//GEN-LAST:event_homeFocusGained

    private void homeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeFocusLost
      
    }//GEN-LAST:event_homeFocusLost

    private void reserveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reserveFocusGained
        
    }//GEN-LAST:event_reserveFocusGained

    private void reserveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reserveFocusLost
       
    }//GEN-LAST:event_reserveFocusLost

    private void galleryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_galleryFocusGained
      
    }//GEN-LAST:event_galleryFocusGained

    private void galleryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_galleryFocusLost
      
    }//GEN-LAST:event_galleryFocusLost

    private void aboutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aboutFocusGained
       
    }//GEN-LAST:event_aboutFocusGained

    private void aboutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aboutFocusLost
    
    }//GEN-LAST:event_aboutFocusLost

    private void gallery1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gallery1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_gallery1FocusGained

    private void gallery1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gallery1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_gallery1FocusLost

    private void gallery1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gallery1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_gallery1MouseEntered

    private void gallery1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gallery1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_gallery1MouseExited

    private void gallery1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gallery1ActionPerformed
      this.sidepanelChoice(5);
    }//GEN-LAST:event_gallery1ActionPerformed

    private void bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseEntered
        Color gold;
        gold = new Color(230,192,104);
        book.setBackground(gold);
        book.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_bookMouseEntered

    private void bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseExited
        Color gold;
        gold = new Color(230,192,104);
        book.setBackground(new Color(255,255,255));
        book.setForeground(gold);
    }//GEN-LAST:event_bookMouseExited

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed

    }//GEN-LAST:event_bookActionPerformed

    private void book1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book1MouseEntered

    private void book1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book1MouseExited

    private void book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book1ActionPerformed

    private void book2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book2MouseEntered

    private void book2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book2MouseExited

    private void book2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book2ActionPerformed

    private void book3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book3MouseEntered

    private void book3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book3MouseExited

    private void book3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book3ActionPerformed

    private void book4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book4MouseEntered

    private void book4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book4MouseExited

    private void book4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book4ActionPerformed

    private void book5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book5MouseEntered

    private void book5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book5MouseExited

    private void book5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book5ActionPerformed

    private void book6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book6MouseEntered

    private void book6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book6MouseExited

    private void book6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book6ActionPerformed

    private void book7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book7MouseEntered

    private void book7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book7MouseExited

    private void book7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book7ActionPerformed

    private void book8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book8MouseEntered

    private void book8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book8MouseExited

    private void book8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book8ActionPerformed

    private void book9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book9MouseEntered

    private void book9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book9MouseExited

    private void book9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book9ActionPerformed

    private void book10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book10MouseEntered

    private void book10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book10MouseExited

    private void book10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book10ActionPerformed

    private void book11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book11MouseEntered

    private void book11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book11MouseExited

    private void book11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book11ActionPerformed

    private void book12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book12MouseEntered

    private void book12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book12MouseExited

    private void book12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book12ActionPerformed

    private void book13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book13MouseEntered

    private void book13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book13MouseExited

    private void book13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book13ActionPerformed

    private void book14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book14MouseEntered

    private void book14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book14MouseExited

    private void book14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book14ActionPerformed

    private void book15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book15MouseEntered

    private void book15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book15MouseExited

    private void book15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book15ActionPerformed

    private void book16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book16MouseEntered

    private void book16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book16MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book16MouseExited

    private void book16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book16ActionPerformed

    private void book17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book17MouseEntered

    private void book17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book17MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book17MouseExited

    private void book17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book17ActionPerformed

    private void book18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book18MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book18MouseEntered

    private void book18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book18MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book18MouseExited

    private void book18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book18ActionPerformed

    private void book19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book19MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book19MouseEntered

    private void book19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book19MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book19MouseExited

    private void book19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book19ActionPerformed

    private void book20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book20MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book20MouseEntered

    private void book20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book20MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book20MouseExited

    private void book20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book20ActionPerformed

    private void book21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book21MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book21MouseEntered

    private void book21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book21MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book21MouseExited

    private void book21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book21ActionPerformed

    private void book22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book22MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book22MouseEntered

    private void book22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book22MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book22MouseExited

    private void book22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book22ActionPerformed

    private void book23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book23MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_book23MouseEntered

    private void book23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book23MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_book23MouseExited

    private void book23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book23ActionPerformed

    /**
     * @param args the command line arguments
     */

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton about;
    public javax.swing.JButton book;
    public javax.swing.JButton book1;
    public javax.swing.JButton book10;
    public javax.swing.JButton book11;
    public javax.swing.JButton book12;
    public javax.swing.JButton book13;
    public javax.swing.JButton book14;
    public javax.swing.JButton book15;
    public javax.swing.JButton book16;
    public javax.swing.JButton book17;
    public javax.swing.JButton book18;
    public javax.swing.JButton book19;
    public javax.swing.JButton book2;
    public javax.swing.JButton book20;
    public javax.swing.JButton book21;
    public javax.swing.JButton book22;
    public javax.swing.JButton book23;
    public javax.swing.JButton book3;
    public javax.swing.JButton book4;
    public javax.swing.JButton book5;
    public javax.swing.JButton book6;
    public javax.swing.JButton book7;
    public javax.swing.JButton book8;
    public javax.swing.JButton book9;
    public javax.swing.JButton contact;
    public javax.swing.JButton gallery;
    public javax.swing.JButton gallery1;
    public javax.swing.JButton home;
    private javax.swing.JPanel insidepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    public javax.swing.JButton logout;
    private javax.swing.JPanel panelReserve;
    private javax.swing.JPanel panelWrapper;
    public javax.swing.JButton reserve;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JLabel textQuote;
    private javax.swing.JLabel textWelcom;
    private javax.swing.JLabel textWelcom4;
    private javax.swing.JPanel toppanel;
    // End of variables declaration//GEN-END:variables
}
