/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivan Adcan
 */
public class AdminChangePW extends javax.swing.JFrame {
    
    int randomCode;

    /**
     * Creates new form Login
     */
    public AdminChangePW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWrapper = new javax.swing.JPanel();
        panelLeft = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        panelRight = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        sendcode = new javax.swing.JButton();
        changepw = new javax.swing.JButton();
        codeInput = new javax.swing.JTextField();
        newPassword = new javax.swing.JPasswordField();
        admin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change Password");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelWrapper.setBackground(new java.awt.Color(230, 192, 104));
        panelWrapper.setMinimumSize(new java.awt.Dimension(800, 500));
        panelWrapper.setPreferredSize(new java.awt.Dimension(800, 500));
        panelWrapper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLeft.setBackground(new java.awt.Color(28, 42, 57));
        panelLeft.setMinimumSize(new java.awt.Dimension(400, 500));
        panelLeft.setPreferredSize(new java.awt.Dimension(400, 500));
        panelLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        panelLeft.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 113, 240, 235));

        panelWrapper.add(panelLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 387, 474));
        panelLeft.getAccessibleContext().setAccessibleName("panelRight");

        panelRight.setBackground(new java.awt.Color(255, 255, 255));
        panelRight.setMinimumSize(new java.awt.Dimension(400, 500));
        panelRight.setPreferredSize(new java.awt.Dimension(400, 500));
        panelRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text1.setBackground(new java.awt.Color(0, 0, 0));
        text1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        text1.setForeground(new java.awt.Color(28, 42, 57));
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setText("Change Password");
        panelRight.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 31, 350, -1));

        sendcode.setBackground(new java.awt.Color(28, 42, 57));
        sendcode.setForeground(new java.awt.Color(255, 255, 255));
        sendcode.setText("Send Code");
        sendcode.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        sendcode.setFocusable(false);
        sendcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendcodeActionPerformed(evt);
            }
        });
        panelRight.add(sendcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 177, -1, 40));

        changepw.setBackground(new java.awt.Color(0, 104, 104));
        changepw.setForeground(new java.awt.Color(255, 255, 255));
        changepw.setText("Change Password");
        changepw.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        changepw.setFocusable(false);
        changepw.setInheritsPopupMenu(true);
        changepw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepwActionPerformed(evt);
            }
        });
        panelRight.add(changepw, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 177, 140, 40));

        codeInput.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        codeInput.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 13))); // NOI18N
        panelRight.add(codeInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, 50));

        newPassword.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        newPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Enter New Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 13))); // NOI18N
        panelRight.add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 400, 50));

        admin.setBackground(new java.awt.Color(0, 0, 0));
        admin.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        admin.setForeground(new java.awt.Color(0, 104, 104));
        admin.setText("Back to Admin");
        admin.setContentAreaFilled(false);
        admin.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        admin.setFocusable(false);
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        panelRight.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 401, -1, 39));

        panelWrapper.add(panelRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 13, 422, 474));
        panelRight.getAccessibleContext().setAccessibleName("panelRight");

        getContentPane().add(panelWrapper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 833, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendcodeActionPerformed
        System.out.println("Send code button clicked!");
        Random random = new Random();
        randomCode = random.nextInt(999999);
        JOptionPane.showMessageDialog(new JFrame(), randomCode, "Send Code", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_sendcodeActionPerformed

    private void changepwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepwActionPerformed
        System.out.println("Change password button clicked!");
        String passwordNew;
            passwordNew = this.newPassword.getText();
        String SUrl, SUser, SPass;
            SUrl = "jdbc:MySQL://localhost:3306/akatsukihotel_user_database";
            SUser = "root";
            SPass = "";
            
        System.out.println("Change password clicked!");
        
        try (Connection con = DriverManager.getConnection(SUrl, SUser, SPass)) {
            Statement st = con.createStatement();
            Statement stChangePW = con.createStatement();
            String queryFindEmail = "SELECT * FROM user WHERE id = 1";
            ResultSet rsFindEmail = st.executeQuery(queryFindEmail);
            
            String codeSendCode = "" + randomCode;
            String code = this.codeInput.getText();
            
            while (rsFindEmail.next()) {
            } if ("".equals(passwordNew)) {
                JOptionPane.showMessageDialog(new JFrame(), "New password is required!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    if (code.equals(codeSendCode)) {
                        String queryPWChange = "UPDATE user "
                                + "SET password = '" + passwordNew + "' "
                                + "WHERE id = 1";
                        stChangePW.executeUpdate(queryPWChange);
                            
                        AdminPWChanged pwchanged = new AdminPWChanged();
                        pwchanged.setVisible(true);
                        pwchanged.pack();
                        pwchanged.setLocationRelativeTo(null);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(new JFrame(), "Wrong code!", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException | HeadlessException e) {
                    System.err.println("Error: Something wrong with the code of the program.");
                    System.err.println("Error Message: " + e.getMessage());
                }
            }
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_changepwActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        Admin a = new Admin();
        a.setVisible(true);
        a.pack();
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_adminActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton admin;
    public javax.swing.JButton changepw;
    private javax.swing.JTextField codeInput;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel panelWrapper;
    public javax.swing.JButton sendcode;
    private javax.swing.JLabel text1;
    // End of variables declaration//GEN-END:variables
}
